services:
  api:
    build: .
    container_name: planning_api
    volumes:
      - ./app:/app
      - /Users/walson/Documents/Cours/5A/PA/scolia-metalibrary-calendar/shared/librustlib.so:/app/libs/librustlib.so
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000