FROM python:3.12-slim

WORKDIR /app

# Crée le dossier qui recevra la librairie partagée
RUN mkdir -p /app/libs

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install python-dotenv
CMD ["echo", "MA GROSSE BIte..."]
COPY . .

ENV PYTHONPATH=/app

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8002"]